# level_up is the amount of blocks you need to break for level up.
#  
foraging:
  oak:
    xp_reward: 1.0
    level_up: 250.0
  birch:
    xp_reward: 1.25
    level_up: 500.0
  acacia:
    xp_reward: 1.5
    level_up: 1000.0
  dark_oak:
    xp_reward: 1.8
    level_up: 2000.0
  spruce:
    xp_reward: 2.2
    level_up: 4000.0
  jungle:
    xp_reward: 3.0
    level_up: 10000.0
  # max level (6) ^ nether stuff:
  crimson:
    global_level_requirement: 40
    xp_reward: 4.0
    level_up: 5000.0
  warped:
    xp_reward: 6.0
    # no levelups

farming:
  wheat:
    xp_reward: 1.0
    level_up: 50.0
  beetroot:
    xp_reward: 1.1
    level_up: 150.0
  carrot:
    xp_reward: 1.2
    level_up: 500.0
  potato:
    xp_reward: 1.3
    level_up: 1000.0
  sugar_cane:
    xp_reward: 1.35
    level_up: 2500.0
  melon:
    xp_reward: 1.4
    level_up: 5000.0
  pumpkin:
    xp_reward: 1.5
    level_up: 10000.0
  # max level (7) ^ nether (and end) stuff:
  nether_wart:
    global_level_requirement: 40
    xp_reward: 2.5
  chorus_flower:
    global_level_requirement: 90
    xp_reward: 4

# no level up stuff cuz it's calculated from island level
combat:
  pillager:
    xp_reward: 0.0
  zombie:
    xp_reward: 2.0
  spider:
    xp_reward: 2.8
  skeleton_creeper:
    xp_reward: 3.4
  zombie_villager:
    xp_reward: 0.0
  piglin:
    xp_reward: 4.0
  hoglin:
    xp_reward: 4.0
  blaze:
    xp_reward: 5.6
  piglin:
    xp_reward: 5.6
  shulker:
    xp_reward: 8.4

mining:
  stone:
    xp_reward: 1.0
    level_up: 50.0
  coal:
    xp_reward: 1.1
    level_up: 25.0
  iron:
    xp_reward: 1.2
    level_up: 100.0
  gold:
    xp_reward: 1.3
    level_up: 300.0
  redstone_lapis:
    xp_reward: 1.2
    level_up: 800.0
  diamond:
    xp_reward: 1.5
    level_up: 1000.0
  emerald:
    xp_reward: 1.7
    level_up: 1250.0
  obsidian:
    xp_reward: 2.0
    level_up: 0.0
  # max level (8) ^ nether (no end for some odd reason) stuff:
  basalt:
    xp_reward: 1.5
    level_up: 500.0
    global_level_requirement: 40
  netherrack_group:
    xp_reward: 0.5
    level_up: 800.0
  blackstone:
    xp_reward: 1.8
    level_up: 1000.0
  soul_group:
    xp_reward: 1.5
    level_up: 1500.0
  ancient_debris:
    xp_reward: 4.0