name: Tierblock
version: '${project.version}'
main: kiul.tierblock.Main
api-version: 1.19
commands:
  givexp:
    description: gives global XP to the user that runs the command.
  modifyvalue:
    description: modifies the value of the given config entry
